In [1]:
import pandas as pd
df =  pd.read_csv("weatherdata.csv")
df

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
0,971.5,0.25,9.0,7.0,10.7,0,0,0
1,972.3,0.97,10.5,6.7,13.5,0,0,0
2,972.4,0.74,6.5,3.9,9.1,0,0,0
3,973.2,0.15,5.1,3.7,7.7,0,0,0
4,975.7,0.12,5.2,2.6,8.3,0,0,0
5,975.9,0.18,4.9,3.8,7.4,0,0,0
6,976.8,0.27,5.8,4.4,7.1,0,0,1
7,976.8,0.35,9.2,7.7,9.2,0,0,0
8,977.3,0.59,11.2,9.3,13.2,0,0,0
9,977.7,0.64,9.0,5.4,12.1,0,0,0
10,978.9,0.14,2.4,0.6,4.7,0,0,0
11,979.1,0.18,8.5,6.5,9.6,0,0,0
12,979.2,0.86,10.4,7.8,13.6,0,0,1
13,979.7,0.31,8.9,6.8,11.0,0,0,0
14,980.6,1.01,3.5,0.6,7.1,0,0,0
15,980.7,0.20,8.6,5.6,9.6,0,0,0
16,980.9,2.12,9.5,5.5,14.8,0,0,1
17,981.1,0.71,8.9,6.5,12.3,0,0,0

In [8]:
df.shape

(18, 8)

In [10]:
rows, columns = df.shape

In [12]:
rows
columns

8

In [2]:
df.head(5)

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
0,971.5,0.25,9.0,7.0,10.7,0,0,0
1,972.3,0.97,10.5,6.7,13.5,0,0,0
2,972.4,0.74,6.5,3.9,9.1,0,0,0
3,973.2,0.15,5.1,3.7,7.7,0,0,0
4,975.7,0.12,5.2,2.6,8.3,0,0,0

In [14]:
df.tail(5)

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
13,979.7,0.31,8.9,6.8,11.0,0,0,0
14,980.6,1.01,3.5,0.6,7.1,0,0,0
15,980.7,0.20,8.6,5.6,9.6,0,0,0
16,980.9,2.12,9.5,5.5,14.8,0,0,1
17,981.1,0.71,8.9,6.5,12.3,0,0,0

In [18]:
# suppose we want particular number of rows and columns 
df[2:5]

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
2,972.4,0.74,6.5,3.9,9.1,0,0,0
3,973.2,0.15,5.1,3.7,7.7,0,0,0
4,975.7,0.12,5.2,2.6,8.3,0,0,0

In [24]:
df.columns

Index(['Pressure', 'global_radiation', 'temp_mean(c)', 'temp_min(c)',
       'temp_max(c)', 'Wind_Speed', 'Wind_Bearing', 'normalized_label'],
      dtype='object')

In [49]:
# if we want the items under particualr column heading teh us ethe following method 
df['Pressure']  # or df.Pressure

0     971.5
1     972.3
2     972.4
3     973.2
4     975.7
5     975.9
6     976.8
7     976.8
8     977.3
9     977.7
10    978.9
11    979.1
12    979.2
13    979.7
14    980.6
15    980.7
16    980.9
17    981.1
Name: Pressure, dtype: float64

In [50]:
type(df['Pressure'])

pandas.core.series.Series

In [3]:
# if we wnat to print the limited columns  then we can use 

df[['Pressure','global_radiation']]

    Pressure  global_radiation
0      971.5              0.25
1      972.3              0.97
2      972.4              0.74
3      973.2              0.15
4      975.7              0.12
5      975.9              0.18
6      976.8              0.27
7      976.8              0.35
8      977.3              0.59
9      977.7              0.64
10     978.9              0.14
11     979.1              0.18
12     979.2              0.86
13     979.7              0.31
14     980.6              1.01
15     980.7              0.20
16     980.9              2.12
17     981.1              0.71

In [6]:
df

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
0,971.5,0.25,9.0,7.0,10.7,0,0,0
1,972.3,0.97,10.5,6.7,13.5,0,0,0
2,972.4,0.74,6.5,3.9,9.1,0,0,0
3,973.2,0.15,5.1,3.7,7.7,0,0,0
4,975.7,0.12,5.2,2.6,8.3,0,0,0
5,975.9,0.18,4.9,3.8,7.4,0,0,0
6,976.8,0.27,5.8,4.4,7.1,0,0,1
7,976.8,0.35,9.2,7.7,9.2,0,0,0
8,977.3,0.59,11.2,9.3,13.2,0,0,0
9,977.7,0.64,9.0,5.4,12.1,0,0,0
10,978.9,0.14,2.4,0.6,4.7,0,0,0
11,979.1,0.18,8.5,6.5,9.6,0,0,0
12,979.2,0.86,10.4,7.8,13.6,0,0,1
13,979.7,0.31,8.9,6.8,11.0,0,0,0
14,980.6,1.01,3.5,0.6,7.1,0,0,0
15,980.7,0.20,8.6,5.6,9.6,0,0,0
16,980.9,2.12,9.5,5.5,14.8,0,0,1
17,981.1,0.71,8.9,6.5,12.3,0,0,0

### Some operation with data framne

In [9]:
df['Pressure'].max()

np.float64(981.1)

In [ ]:
float(df['Pressure'].mean())

# or df['Preessure'].mean()

977.2111111111111

In [ ]:
# df['Pressure'].min()
float(df['Pressure'].min())

971.5

In [12]:
float(df['Pressure'].std())

3.1577894145949914

In [14]:
# Printing the stat of the data set quickly
df.describe()

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.0,18.0,18.000000
mean,977.211111,0.543889,7.616667,5.244444,10.055556,0.0,0.0,0.166667
std,3.157789,0.496756,2.567730,2.390231,2.778536,0.0,0.0,0.383482
min,971.500000,0.120000,2.400000,0.600000,4.700000,0.0,0.0,0.000000
25%,975.750000,0.185000,5.350000,3.825000,7.850000,0.0,0.0,0.000000
50%,977.500000,0.330000,8.750000,5.550000,9.600000,0.0,0.0,0.000000
75%,979.575000,0.732500,9.150000,6.775000,12.250000,0.0,0.0,0.000000
max,981.100000,2.120000,11.200000,9.300000,14.800000,0.0,0.0,1.000000

In [16]:
df [df.global_radiation>=1]

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
14,980.6,1.01,3.5,0.6,7.1,0,0,0
16,980.9,2.12,9.5,5.5,14.8,0,0,1

In [ ]:
df[df.global_radiation==df.global_radiation.max()]
# df[df.global_radiation==df['global_radiation'].max()]  # comma seperated data then use this

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
16,980.9,2.12,9.5,5.5,14.8,0,0,1

In [24]:
#  if you dont want all  the columns then you can mention wehatever you wants
df[['Pressure','global_radiation']][df.global_radiation==df.global_radiation.max()]

    Pressure  global_radiation
16     980.9              2.12

In [57]:
import pandas as pd

In [2]:
df = pd.read_csv('weather_data.csv')
df

         Day  Temperature   event  Wind speed
0   1/4/2026            26  Rainy           6
1   2/4/2026            35  Sunny           7
2   3/4/2026            46  Sunny           4
3   4/4/2026            32  Sunny           5
4   5/4/2026            28   Snow           7
5   6/4/2026            34  Sunny           5
6   7/4/2026            30  Rainy           6
7   8/4/2026            27   Snow           7
8   9/4/2026            38  Sunny           5
9  10/4/2026            31  Rainy           4

In [71]:
df.columns

Index(['Day', 'Temperature ', 'event', 'Wind speed'], dtype='str')

In [72]:
df.set_index('Day',inplace=True)
df

           Temperature   event  Wind speed
Day
1/4/2026             26  Rainy           6
2/4/2026             35  Sunny           7
3/4/2026             46  Sunny           4
4/4/2026             32  Sunny           5
5/4/2026             28   Snow           7
6/4/2026             34  Sunny           5
7/4/2026             30  Rainy           6
8/4/2026             27   Snow           7
9/4/2026             38  Sunny           5
10/4/2026            31  Rainy           4

In [ ]:
df.loc['4/4/2026']

# by this method you can view any of the row details

Temperature        32
event           Sunny
Wind speed          5
Name: 4/4/2026, dtype: object

In [75]:
df.reset_index(inplace= True)

In [76]:
df.set_index('event',inplace=True)

In [78]:
df.loc['Snow']

            Day  Temperature   Wind speed
event
Snow   5/4/2026            28           7
Snow   8/4/2026            27           7

In [6]:
df.reset_index(inplace=True)

In [7]:
df.set_index('Wind speed',inplace=True)
df

            index        Day  Temperature   event
Wind speed
6               0   1/4/2026            26  Rainy
7               1   2/4/2026            35  Sunny
4               2   3/4/2026            46  Sunny
5               3   4/4/2026            32  Sunny
7               4   5/4/2026            28   Snow
5               5   6/4/2026            34  Sunny
6               6   7/4/2026            30  Rainy
7               7   8/4/2026            27   Snow
5               8   9/4/2026            38  Sunny
4               9  10/4/2026            31  Rainy

In [5]:
df.index

RangeIndex(start=0, stop=18, step=1)