## Deffernt ways of creating Data Frames

### Using CSV

In [2]:
import pandas as pd

pd.read_csv('weather_data.csv')

         Day  Temperature   event  Wind speed
0   1/4/2026            26  Rainy           6
1   2/4/2026            35  Sunny           7
2   3/4/2026            46  Sunny           4
3   4/4/2026            32  Sunny           5
4   5/4/2026            28   Snow           7
5   6/4/2026            34  Sunny           5
6   7/4/2026            30  Rainy           6
7   8/4/2026            27   Snow           7
8   9/4/2026            38  Sunny           5
9  10/4/2026            31  Rainy           4

### Using excel

In [1]:
import pandas as pd

df = pd.read_excel("Weather_data.xlsx", sheet_name="Sheet1")

print(df)

         Day  Temperature  Climate
0 2026-01-01            35   Rainy
1 2026-01-02            32   Snow
2 2026-01-03            34   Snow
3 2026-01-04            35   Sunny
4 2026-01-05            31   Rainy
5 2026-01-06            30   Snow
6 2026-01-07            32   Sunny
7 2026-01-08            34   Sunny
8 2026-01-09            35   Snow
9 2026-01-10            31   Rainy

### Using Python Dictonary

In [5]:
# Make one python dectionary of required data set and then read it as a data frame 

weather_data = {
    'day' : ['1/4/2026', '2/4/2026', '3/4/2026', '4/4/2026'],
    'temperature' : [32, 28, 34, 35],
    'climate' : ['Sunny','snow','sunny','sunny']
}
pd.DataFrame(weather_data)

        day  temperature climate
0  1/4/2026           32   Sunny
1  2/4/2026           28    snow
2  3/4/2026           34   sunny
3  4/4/2026           35   sunny

### Using Python Tuples list

In [6]:
weather_data = [
    ('1/4/2026',32,6,'Sunny'),
    ('2/4/2026',28,4,'snow'),
    ('3/4/2026',34,5,'sunny'),
    ('4/4/2026',35,3,'sunny')
]
pd.DataFrame(weather_data, columns=["day","tempertaure","windspeed","climate"])

        day  tempertaure  windspeed climate
0  1/4/2026           32          6   Sunny
1  2/4/2026           28          4    snow
2  3/4/2026           34          5   sunny
3  4/4/2026           35          3   sunny

### Using list of dictionaries

In [8]:
weather_data = [
    {'day':'1/4/2026', 'temperature':32, 'windspeed':6, 'climate':'sunny'},
    {'day':'2/4/2026', 'temperature':28, 'windspeed':4, 'climate':'snow'},
    {'day':'3/4/2026', 'temperature':34, 'windspeed':5, 'climate':'sunny'},
    {'day':'4/4/2026', 'temperature':35, 'windspeed':3, 'climate':'sunny'}
]
pd.DataFrame(weather_data)

        day  temperature  windspeed climate
0  1/4/2026           32          6   sunny
1  2/4/2026           28          4    snow
2  3/4/2026           34          5   sunny
3  4/4/2026           35          3   sunny