In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("new_york_weatherdata.csv")
df

          day  temperature  wind_speed   event
0  01-01-2026         32.0         6.0   Sunny
1  04-01-2026         35.0         7.0  Cloudy
2  05-01-2026          NaN         5.0    Rain
3  06-01-2026         28.0         NaN   Sunny
4  07-01-2026         30.0         4.0     NaN
5  08-01-2026         31.0         8.0  Cloudy
6  09-01-2026          NaN         NaN    Rain
7  10-01-2026         29.0         6.0   Sunny
8  11-01-2026         33.0         NaN  Cloudy
9  12-01-2026         27.0         5.0    Rain

In [4]:
df = pd.read_csv("new_york_weatherdata.csv",parse_dates=["day"])
df
type(df.day[0])

pandas.Timestamp

In [ ]:
# to convert into a day column
df = pd.read_csv("new_york_weatherdata.csv",parse_dates=["day"])
df.set_index('day',inplace=True)
df

            temperature  wind_speed   event
day
2026-01-01         32.0         6.0   Sunny
2026-04-01         35.0         7.0  Cloudy
2026-05-01          NaN         5.0    Rain
2026-06-01         28.0         NaN   Sunny
2026-07-01         30.0         4.0     NaN
2026-08-01         31.0         8.0  Cloudy
2026-09-01          NaN         NaN    Rain
2026-10-01         29.0         6.0   Sunny
2026-11-01         33.0         NaN  Cloudy
2026-12-01         27.0         5.0    Rain

In [5]:
new_df = df.fillna(0)
new_df

         day  temperature  wind_speed   event
0 2026-01-01         32.0         6.0   Sunny
1 2026-04-01         35.0         7.0  Cloudy
2 2026-05-01          0.0         5.0    Rain
3 2026-06-01         28.0         0.0   Sunny
4 2026-07-01         30.0         4.0       0
5 2026-08-01         31.0         8.0  Cloudy
6 2026-09-01          0.0         0.0    Rain
7 2026-10-01         29.0         6.0   Sunny
8 2026-11-01         33.0         0.0  Cloudy
9 2026-12-01         27.0         5.0    Rain

In [6]:
# if you want to specify different values for different columns

new_df = df.fillna({
    'temperature' : 0,
    'wind_speed' : 0,
    'event':'no event'
})
new_df

          day  temperature  wind_speed   event
0  01-01-2026         32.0         6.0   Sunny
1  04-01-2026         35.0         7.0  Cloudy
2  05-01-2026         35.0         5.0    Rain
3  06-01-2026         28.0         5.0   Sunny
4  07-01-2026         30.0         4.0   Sunny
5  08-01-2026         31.0         8.0  Cloudy
6  09-01-2026         31.0         8.0    Rain
7  10-01-2026         29.0         6.0   Sunny
8  11-01-2026         33.0         6.0  Cloudy
9  12-01-2026         27.0         5.0    Rain

In [6]:
# its not good to put zero in all cases so just forward the previous values 
new_df = df = df.ffill()
new_df

         day  temperature  wind_speed   event
0 2026-01-01         32.0         6.0   Sunny
1 2026-04-01         35.0         7.0  Cloudy
2 2026-05-01         35.0         5.0    Rain
3 2026-06-01         28.0         5.0   Sunny
4 2026-07-01         30.0         4.0   Sunny
5 2026-08-01         31.0         8.0  Cloudy
6 2026-09-01         31.0         8.0    Rain
7 2026-10-01         29.0         6.0   Sunny
8 2026-11-01         33.0         6.0  Cloudy
9 2026-12-01         27.0         5.0    Rain

In [11]:
new_df = df.bfill()
new_df

         day  temperature  wind_speed   event
0 2026-01-01         32.0         6.0   Sunny
1 2026-04-01         35.0         7.0  Cloudy
2 2026-05-01         35.0         5.0    Rain
3 2026-06-01         28.0         5.0   Sunny
4 2026-07-01         30.0         4.0   Sunny
5 2026-08-01         31.0         8.0  Cloudy
6 2026-09-01         31.0         8.0    Rain
7 2026-10-01         29.0         6.0   Sunny
8 2026-11-01         33.0         6.0  Cloudy
9 2026-12-01         27.0         5.0    Rain

In [10]:
df

         day  temperature  wind_speed   event
0 2026-01-01         32.0         6.0   Sunny
1 2026-04-01         35.0         7.0  Cloudy
2 2026-05-01         35.0         5.0    Rain
3 2026-06-01         28.0         5.0   Sunny
4 2026-07-01         30.0         4.0   Sunny
5 2026-08-01         31.0         8.0  Cloudy
6 2026-09-01         31.0         8.0    Rain
7 2026-10-01         29.0         6.0   Sunny
8 2026-11-01         33.0         6.0  Cloudy
9 2026-12-01         27.0         5.0    Rain

In [12]:
df = pd.read_csv('new_york_weatherdata.csv')
new_df = df.bfill()
new_df

          day  temperature  wind_speed   event
0  01-01-2026         32.0         6.0   Sunny
1  04-01-2026         35.0         7.0  Cloudy
2  05-01-2026         28.0         5.0    Rain
3  06-01-2026         28.0         4.0   Sunny
4  07-01-2026         30.0         4.0  Cloudy
5  08-01-2026         31.0         8.0  Cloudy
6  09-01-2026         29.0         6.0    Rain
7  10-01-2026         29.0         6.0   Sunny
8  11-01-2026         33.0         5.0  Cloudy
9  12-01-2026         27.0         5.0    Rain