In [2]:
import pandas as pd
df = pd.read_csv('stock_data(csv).csv',skiprows=1)
df

   GOOGL          27.82     87   845         Larry Page
0    WMT           4.61  484.0    65               n.a.
1   MSFT             -1   85.0    64         Bill Gates
2    RIL  not available   50.0  1023      Mukesh Ambani
3   TATA            5.6   -1.5  n.a.         Ratan Tata
4   AAPL           31.5   -2.4   189           Tim Cook
5   AMZN           12.7  514.0   134         Jeff Bezos
6   TSLA            8.2   96.0   248          Elon Musk
7   NFLX            9.4   39.0   415       Ted Sarandos
8   META           14.8  134.0   312    Mark Zuckerberg
9   NVDA           21.7   61.0   950       Jensen Huang
10   IBM            6.1   60.0   143     Arvind Krishna
11  ORCL            5.4   49.0   118      Larry Ellison
12  INTC           -2.4   77.0    35      Pat Gelsinger
13   AMD            3.7   22.0   176            Lisa Su
14  ADBE           11.5   19.0   520   Shantanu Narayen
15  CSCO            3.9   57.0    49      Chuck Robbins
16   SAP            6.8   35.0   168    Christian Klein
17  SONY            7.2   88.0    91  Kenichiro Yoshida
18  INFY            3.2   18.0    22       Salil Parekh
19   TCS            4.5   29.0    42      K Krithivasan
20   HCL            2.9   15.0    18      C Vijayakumar
21  SHOP           n.a.    7.0    76         Tobi Lutke
22  UBER           -0.5   38.0    71  Dara Khosrowshahi
23  LYFT           -1.2    4.0    14       David Risher
24  BABA            8.1  126.0    79           Eddie Wu
25  PYPL            4.3   29.0    66        Alex Chriss
26   DIS            3.4   89.0   104           Bob Iger
27    KO            2.7   45.0    63      James Quincey
28   PEP            6.2   91.0   174     Ramon Laguarta

In [5]:
# alterantive to the above method is this 

df = pd.read_csv('stock_data(csv).csv',header=1)
df

   GOOGL          27.82     87   845         Larry Page
0    WMT           4.61  484.0    65               n.a.
1   MSFT             -1   85.0    64         Bill Gates
2    RIL  not available   50.0  1023      Mukesh Ambani
3   TATA            5.6   -1.5  n.a.         Ratan Tata
4   AAPL           31.5   -2.4   189           Tim Cook
5   AMZN           12.7  514.0   134         Jeff Bezos
6   TSLA            8.2   96.0   248          Elon Musk
7   NFLX            9.4   39.0   415       Ted Sarandos
8   META           14.8  134.0   312    Mark Zuckerberg
9   NVDA           21.7   61.0   950       Jensen Huang
10   IBM            6.1   60.0   143     Arvind Krishna
11  ORCL            5.4   49.0   118      Larry Ellison
12  INTC           -2.4   77.0    35      Pat Gelsinger
13   AMD            3.7   22.0   176            Lisa Su
14  ADBE           11.5   19.0   520   Shantanu Narayen
15  CSCO            3.9   57.0    49      Chuck Robbins
16   SAP            6.8   35.0   168    Christian Klein
17  SONY            7.2   88.0    91  Kenichiro Yoshida
18  INFY            3.2   18.0    22       Salil Parekh
19   TCS            4.5   29.0    42      K Krithivasan
20   HCL            2.9   15.0    18      C Vijayakumar
21  SHOP           n.a.    7.0    76         Tobi Lutke
22  UBER           -0.5   38.0    71  Dara Khosrowshahi
23  LYFT           -1.2    4.0    14       David Risher
24  BABA            8.1  126.0    79           Eddie Wu
25  PYPL            4.3   29.0    66        Alex Chriss
26   DIS            3.4   89.0   104           Bob Iger
27    KO            2.7   45.0    63      James Quincey
28   PEP            6.2   91.0   174     Ramon Laguarta

In [ ]:
# in the reverse case if you dont have the csv file actual index header then you can add the raandom header 
df = pd.read_csv('stock_data(csv).csv', header=None)
df
'''by giving header=None you can see that kernel is automatically asigning the the numberd index its fine but not thats ok to be have so
 further what we can do lets see in next code cell'''

'by giving header=None you can see that kernel is automatically asigning the the numberd index its fine but not thats ok to be have so\n further waht we can do lets isee in next code cell'

In [ ]:
'''Ok if you dont want the numberd index or header than you can give the names of your columns'''
df = pd.read_csv('stock_data(csv).csv',header=None, names=['tickers','eps','revenue','price','people'])
df
# so you can see that you bpught it tothe original form....

In [ ]:
# suppose your csv file has large number of but you want to read or frame few of them then use below method
df = pd.read_csv('stock_data(csv).csv',nrows=3)
df

In [ ]:
# if csv file have any problems like not available or na reaad it as a not a number 
df = pd.read_csv('stock_data(csv).csv',na_values=["not available","n.a."])
df

In [7]:
# if you dont want negative values in sme case but the same time there may be negative in other then
df = pd.read_csv('stock_data(csv).csv',na_values={
    'revenue': ["not available","n.a.",-1],
    'eps': ["not available","n.a.",]
})
df

   tickers    eps  revenue price             people
0    GOOGL  27.82     87.0   845         Larry Page
1      WMT   4.61    484.0    65               n.a.
2     MSFT  -1.00     85.0    64         Bill Gates
3      RIL    NaN     50.0  1023      Mukesh Ambani
4     TATA   5.60     -1.5  n.a.         Ratan Tata
5     AAPL  31.50     -2.4   189           Tim Cook
6     AMZN  12.70    514.0   134         Jeff Bezos
7     TSLA   8.20     96.0   248          Elon Musk
8     NFLX   9.40     39.0   415       Ted Sarandos
9     META  14.80    134.0   312    Mark Zuckerberg
10    NVDA  21.70     61.0   950       Jensen Huang
11     IBM   6.10     60.0   143     Arvind Krishna
12    ORCL   5.40     49.0   118      Larry Ellison
13    INTC  -2.40     77.0    35      Pat Gelsinger
14     AMD   3.70     22.0   176            Lisa Su
15    ADBE  11.50     19.0   520   Shantanu Narayen
16    CSCO   3.90     57.0    49      Chuck Robbins
17     SAP   6.80     35.0   168    Christian Klein
18    SONY   7.20     88.0    91  Kenichiro Yoshida
19    INFY   3.20     18.0    22       Salil Parekh
20     TCS   4.50     29.0    42      K Krithivasan
21     HCL   2.90     15.0    18      C Vijayakumar
22    SHOP    NaN      7.0    76         Tobi Lutke
23    UBER  -0.50     38.0    71  Dara Khosrowshahi
24    LYFT  -1.20      4.0    14       David Risher
25    BABA   8.10    126.0    79           Eddie Wu
26    PYPL   4.30     29.0    66        Alex Chriss
27     DIS   3.40     89.0   104           Bob Iger
28      KO   2.70     45.0    63      James Quincey
29     PEP   6.20     91.0   174     Ramon Laguarta

In [8]:
# if more negative values other  than 1 then and also other as nan in another columns 

df.loc[df['revenue'] < 0, 'revenue'] = pd.NA
df.loc[df['eps'] == "not available", 'eps'] = pd.NA
df

   tickers    eps  revenue price             people
0    GOOGL  27.82     87.0   845         Larry Page
1      WMT   4.61    484.0    65               n.a.
2     MSFT  -1.00     85.0    64         Bill Gates
3      RIL    NaN     50.0  1023      Mukesh Ambani
4     TATA   5.60      NaN  n.a.         Ratan Tata
5     AAPL  31.50      NaN   189           Tim Cook
6     AMZN  12.70    514.0   134         Jeff Bezos
7     TSLA   8.20     96.0   248          Elon Musk
8     NFLX   9.40     39.0   415       Ted Sarandos
9     META  14.80    134.0   312    Mark Zuckerberg
10    NVDA  21.70     61.0   950       Jensen Huang
11     IBM   6.10     60.0   143     Arvind Krishna
12    ORCL   5.40     49.0   118      Larry Ellison
13    INTC  -2.40     77.0    35      Pat Gelsinger
14     AMD   3.70     22.0   176            Lisa Su
15    ADBE  11.50     19.0   520   Shantanu Narayen
16    CSCO   3.90     57.0    49      Chuck Robbins
17     SAP   6.80     35.0   168    Christian Klein
18    SONY   7.20     88.0    91  Kenichiro Yoshida
19    INFY   3.20     18.0    22       Salil Parekh
20     TCS   4.50     29.0    42      K Krithivasan
21     HCL   2.90     15.0    18      C Vijayakumar
22    SHOP    NaN      7.0    76         Tobi Lutke
23    UBER  -0.50     38.0    71  Dara Khosrowshahi
24    LYFT  -1.20      4.0    14       David Risher
25    BABA   8.10    126.0    79           Eddie Wu
26    PYPL   4.30     29.0    66        Alex Chriss
27     DIS   3.40     89.0   104           Bob Iger
28      KO   2.70     45.0    63      James Quincey
29     PEP   6.20     91.0   174     Ramon Laguarta

In [11]:
df.to_csv('new.csv',index=False)

In [12]:
df.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='str')

In [15]:
# If you dont want all the columns then 
df.to_csv("new.csv",columns=['tickers', 'eps'])

In [16]:
df.to_csv("new.csv",header=False)

### Reading excel file

In [17]:
import pandas as pd

pd.read_excel("stock_data(excel).xlsx")

   ticker            eps  revenue price             people
0   GOOGL          27.82       87   845         Larry Page
1     WMT           4.61      484    65               n.a.
2    MSFT             -1       85    64         Bill Gates
3     RIL  not available       50  1023      Mukesh Ambani
4    TATA            5.6       -1  n.a.         Ratan Tata
5    AAPL           31.5      394   189           Tim Cook
6    AMZN           12.7      514   134         Jeff Bezos
7    TSLA            8.2       96   248          Elon Musk
8    NFLX            9.4       39   415       Ted Sarandos
9    META           14.8      134   312    Mark Zuckerberg
10   NVDA           21.7       61   950       Jensen Huang
11    IBM            6.1       60   143     Arvind Krishna
12   ORCL            5.4       49   118      Larry Ellison
13   INTC           -2.4       77    35      Pat Gelsinger
14    AMD            3.7       22   176            Lisa Su
15   ADBE           11.5       19   520   Shantanu Narayen
16   CSCO            3.9       57    49      Chuck Robbins
17    SAP            6.8       35   168    Christian Klein
18   SONY            7.2       88    91  Kenichiro Yoshida
19   INFY            3.2       18    22       Salil Parekh
20    TCS            4.5       29    42      K Krithivasan
21    HCL            2.9       15    18      C Vijayakumar
22   SHOP           n.a.        7    76         Tobi Lutke
23   UBER           -0.5       38    71  Dara Khosrowshahi
24   LYFT           -1.2        4    14       David Risher
25   BABA            8.1      126    79           Eddie Wu
26   PYPL            4.3       29    66        Alex Chriss
27    DIS            3.4       89   104           Bob Iger
28     KO            2.7       45    63      James Quincey
29    PEP            6.2       91   174     Ramon Laguarta

In [ ]:

def convert_people_cell(cell):
    if cell == "n.a.":
        return "Sam walton"
    return cell

def convert_eps_cell(cell):
    if cell == "not available":
        return None
    return cell
pd.read_excel("stock_data(excel).xlsx",converters={
    'people' : convert_people_cell,
    'eps' : convert_eps_cell
})

   ticker    eps  revenue price             people
0   GOOGL  27.82       87   845         Larry Page
1     WMT   4.61      484    65         Sam walton
2    MSFT  -1.00       85    64         Bill Gates
3     RIL    NaN       50  1023      Mukesh Ambani
4    TATA   5.60       -1  n.a.         Ratan Tata
5    AAPL  31.50      394   189           Tim Cook
6    AMZN  12.70      514   134         Jeff Bezos
7    TSLA   8.20       96   248          Elon Musk
8    NFLX   9.40       39   415       Ted Sarandos
9    META  14.80      134   312    Mark Zuckerberg
10   NVDA  21.70       61   950       Jensen Huang
11    IBM   6.10       60   143     Arvind Krishna
12   ORCL   5.40       49   118      Larry Ellison
13   INTC  -2.40       77    35      Pat Gelsinger
14    AMD   3.70       22   176            Lisa Su
15   ADBE  11.50       19   520   Shantanu Narayen
16   CSCO   3.90       57    49      Chuck Robbins
17    SAP   6.80       35   168    Christian Klein
18   SONY   7.20       88    91  Kenichiro Yoshida
19   INFY   3.20       18    22       Salil Parekh
20    TCS   4.50       29    42      K Krithivasan
21    HCL   2.90       15    18      C Vijayakumar
22   SHOP    NaN        7    76         Tobi Lutke
23   UBER  -0.50       38    71  Dara Khosrowshahi
24   LYFT  -1.20        4    14       David Risher
25   BABA   8.10      126    79           Eddie Wu
26   PYPL   4.30       29    66        Alex Chriss
27    DIS   3.40       89   104           Bob Iger
28     KO   2.70       45    63      James Quincey
29    PEP   6.20       91   174     Ramon Laguarta

### Writing excel file

In [34]:
df.to_excel("new.xlsx",sheet_name='stocks',startrow=1,startcol=2,index=None)

In [41]:
import pandas as pd

df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather = pd.DataFrame({
    'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
    'temperature': [32, 35, 28],
    'event': ['Rain', 'Sunny', 'Snow']

})

with pd.ExcelWriter('stock_weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")